name: Trigger action on CRON
on:
  [push]
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '*/1 * * * *'
jobs:
  test-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: run every minute
        run: echo "Running every minute"
